### PR TITLE
#7 mongo db

### PR DESCRIPTION
**Pull request by Reithger**
Issue #7 is long solved, will start new one for next step.

### CODE REVIEW

**Review by ShakeDewan — COMMENTED** [review]
This is great, but shouldn't this be integrated into the server rather than in the database repository based on our discussion last meeting? 

By that I mean that at least some of the functionality should be split off into the server. That's something that we should discuss before merging.

**Comment by Reithger** [comment]
> This is great, but shouldn't this be integrated into the server rather than in the database repository based on our discussion last meeting?
> By that I mean that at least some of the functionality should be split off into the server. That's something that we should discuss before merging.

In that case, this repository is basically going to be empty because the database doesn't actively do anything, and all the files here technically belong with the server.

For the sake of my developing things and being able to make new issues for furthering work on the SPARQL/Mongo stuff, merging this will help me and make these files more accessible to other groups.

**Comment by ShakeDewan** [comment]
> > This is great, but shouldn't this be integrated into the server rather than in the database repository based on our discussion last meeting?
> > By that I mean that at least some of the functionality should be split off into the server. That's something that we should discuss before merging.
> 
> In that case, this repository is basically going to be empty because the database doesn't actively do anything, and all the files here technically belong with the server.
> 
> For the sake of my developing things and being able to make new issues for furthering work on the SPARQL/Mongo stuff, merging this will help me and make these files more accessible to other groups.

Okay, in that case I will approve the pr, but it may help the server team if you can keep it easy for them to understand the functionality and also easy to remove it when the time comes. Some sort of modularization would be how I would do this.

**Review by ShakeDewan — APPROVED** [review]
Looks good, but please see my other comment.

**Pull request merged**
